#!/usr/bin/env python3
"""
CNN Inference from Spectrum Trace Files

This script reads spectrum data from the .tr trace files generated by
spectrum-shadow-sim and runs CNN inference every 100 seconds.

Usage:
    python cnn_from_trace.py --trace-dir ./spectrum-logs --interval 100

The script:
1. Waits for the cnn.tr trace file to be created
2. Adds 1ms buffer after file creation
3. Runs CNN inference on the trace data
4. Logs results to curr_cnn_logs directory
"""

import os
import sys
import time
import argparse
import threading
import random
import numpy as np
import json
import logging
from collections import deque
from datetime import datetime

# Add path for CNN modules
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)  # custom-ns-3 root
CNN_PATH = os.path.join(PROJECT_ROOT, 'contrib', 'spectrum-pipe-streamer', 'examples')
sys.path.insert(0, CNN_PATH)

# Setup logging - output to curr_cnn_logs in project root
CNN_LOG_DIR = os.path.join(PROJECT_ROOT, 'curr_cnn_logs')
os.makedirs(CNN_LOG_DIR, exist_ok=True)

logging.basicConfig(
    filename=os.path.join(CNN_LOG_DIR, 'cnn_inference.log'),
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

# Try to import CNN modules
try:
    from CNN.image_one import create_in_memory_image
    from CNN.dutycycle_model import DeepSpectrum
    import torch
    CNN_AVAILABLE = True
    print("[CNN] CNN modules loaded successfully")
except ImportError as e:
    print(f"[CNN] Warning: CNN modules not available: {e}")
    print("[CNN] Running in data-collection-only mode")
    CNN_AVAILABLE = False

# ============================================================================
# CONFIGURATION
# ============================================================================

class Config:
    # Trace file settings
    trace_dir = os.path.join(PROJECT_ROOT, 'spectrum-logs')
    
    # CNN trace file pattern (cnn_1.tr, cnn_2.tr, etc.)
    cnn_trace_pattern = 'cnn_'
    
    # Buffer time after file creation (milliseconds)
    file_wait_buffer_ms = 0.1  # 0.1ms buffer
    
    # Max wait time for trace file (seconds)
    max_wait_time = 300  # 5 minutes
    
    # CNN inference interval (seconds)
    inference_interval = 100.0
    
    # Max concurrent CNN processing threads
    max_workers = 4
    
    # CNN model paths (relative to CNN_PATH)
    model_2_4ghz = 'CNN-model-weights/bay2.pt'
    model_5ghz = 'CNN-model-weights/5ghz.pt'
    
    # Band configurations
    bands = {
        '2.4GHz': {
            'pattern': 'spectrum-2.4ghz',
            'freq_start': 2.4e9,
            'freq_resolution': 100e3,
            'num_bins': 1000,
            'tech_names': ['WiFi', 'Bluetooth', 'Zigbee', 'Microwave', 'Cordless']
        },
        '5GHz': {
            'pattern': 'spectrum-5ghz',
            'freq_start': 5.0e9,
            'freq_resolution': 100e3,
            'num_bins': 2500,
            'tech_names': ['WiFi', 'Radar']
        }
    }
    
    # Output directory - curr_cnn_logs in project root
    output_dir = CNN_LOG_DIR
    
    # Time resolution in trace files (seconds)
    time_resolution = 0.01  # 10ms


# ============================================================================
# TRACE FILE READER
# ============================================================================

class TraceFileReader:
    """Reads and parses spectrum trace (.tr) files"""
    
    def __init__(self, trace_dir: str):
        self.trace_dir = trace_dir
        self.last_read_position = {}  # Track read position per file
        
    def find_latest_trace(self, pattern: str) -> str:
        """Find the most recent trace file matching pattern"""
        if not os.path.exists(self.trace_dir):
            return None
            
        files = []
        for f in os.listdir(self.trace_dir):
            if pattern in f and f.endswith('.tr'):
                files.append(os.path.join(self.trace_dir, f))
        
        if not files:
            return None
            
        # Return most recently modified
        return max(files, key=os.path.getmtime)
    
    def read_new_data(self, filepath: str, max_lines: int = 100000) -> list:
        """Read new data from trace file since last read"""
        if not filepath or not os.path.exists(filepath):
            return []
        
        # Get last read position
        last_pos = self.last_read_position.get(filepath, 0)
        
        data = []
        try:
            with open(filepath, 'r') as f:
                f.seek(last_pos)
                lines_read = 0
                
                for line in f:
                    lines_read += 1
                    if lines_read > max_lines:
                        break
                        
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    
                    try:
                        parts = line.split()
                        if len(parts) >= 4:
                            # Format: node_id time freq psd
                            node_id = int(parts[0])
                            timestamp = float(parts[1])
                            freq = float(parts[2])
                            psd = float(parts[3])
                            data.append({
                                'node_id': node_id,
                                'time': timestamp,
                                'freq': freq,
                                'psd': psd
                            })
                        elif len(parts) >= 3:
                            # Format: time freq psd (no node_id)
                            timestamp = float(parts[0])
                            freq = float(parts[1])
                            psd = float(parts[2])
                            data.append({
                                'node_id': 0,
                                'time': timestamp,
                                'freq': freq,
                                'psd': psd
                            })
                    except (ValueError, IndexError):
                        continue
                
                # Update read position
                self.last_read_position[filepath] = f.tell()
                
        except Exception as e:
            logging.error(f"Error reading trace file: {e}")
            
        return data
    
    def read_time_window(self, filepath: str, start_time: float, end_time: float) -> np.ndarray:
        """Read data within a specific time window and return as 2D array"""
        if not filepath or not os.path.exists(filepath):
            return None
        
        data = []
        try:
            with open(filepath, 'r') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    
                    try:
                        parts = line.split()
                        if len(parts) >= 3:
                            if len(parts) >= 4:
                                timestamp = float(parts[1])
                                freq = float(parts[2])
                                psd = float(parts[3])
                            else:
                                timestamp = float(parts[0])
                                freq = float(parts[1])
                                psd = float(parts[2])
                            
                            if start_time <= timestamp <= end_time:
                                data.append([timestamp, freq, psd])
                    except (ValueError, IndexError):
                        continue
                        
        except Exception as e:
            logging.error(f"Error reading time window: {e}")
            return None
        
        if not data:
            return None
            
        return np.array(data)


# ============================================================================
# CNN INFERENCE ENGINE
# ============================================================================

class CNNInferenceEngine:
    """Handles CNN model loading and inference"""
    
    def __init__(self, config: Config):
        self.config = config
        self.models = {}
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        
        if CNN_AVAILABLE:
            self._load_models()
    
    def _load_models(self):
        """Load CNN models for each band"""
        for band_name, band_config in self.config.bands.items():
            model_file = self.config.model_2_4ghz if '2.4' in band_name else self.config.model_5ghz
            model_path = os.path.join(CNN_PATH, model_file)
            
            if os.path.exists(model_path):
                try:
                    model = DeepSpectrum(device=self.device, pretrained_weights_path=model_path)
                    self.models[band_name] = model
                    print(f"[CNN] Loaded model for {band_name}: {model_path}")
                except Exception as e:
                    print(f"[CNN] Failed to load model for {band_name}: {e}")
                    self.models[band_name] = None
            else:
                print(f"[CNN] Model not found for {band_name}: {model_path}")
                self.models[band_name] = None
    
    def canvas_loader(self, data_array: np.ndarray) -> np.ndarray:
        """Convert raw data to normalized canvas (spectrogram)"""
        time_col = data_array[:, 0]
        freq_col = data_array[:, 1]
        energy_col = data_array[:, 2]
        
        unique_times = np.unique(time_col)
        unique_freqs = np.unique(freq_col)
        
        T = len(unique_times)
        F = len(unique_freqs)
        
        if T * F != len(data_array):
            # Handle irregular grid by interpolation
            print(f"[CNN] Warning: Irregular grid T={T}, F={F}, samples={len(data_array)}")
            # Take only complete frames
            complete_samples = (len(data_array) // F) * F
            if complete_samples == 0:
                return None
            data_array = data_array[:complete_samples]
            T = complete_samples // F
            energy_col = data_array[:, 2]
        
        # Reshape to (freq, time)
        canvas = energy_col.reshape(T, F).T
        
        # Column-wise normalization
        col_min = canvas.min(axis=0, keepdims=True)
        col_max = canvas.max(axis=0, keepdims=True)
        canvas_std = (canvas - col_min) / (col_max - col_min + 1e-12)
        
        return canvas_std.astype(np.float32)
    
    def run_inference(self, data: np.ndarray, band_name: str) -> dict:
        """Run CNN inference on spectrum data"""
        if not CNN_AVAILABLE:
            return self._dummy_inference(band_name)
        
        model = self.models.get(band_name)
        if model is None:
            return self._dummy_inference(band_name)
        
        try:
            # Create canvas/spectrogram
            canvas = self.canvas_loader(data)
            if canvas is None:
                return None
            
            # Run inference
            with torch.no_grad():
                preds = model.predict(canvas)
            
            # Process predictions
            pred_np = preds.cpu().numpy() if hasattr(preds, 'cpu') else np.array(preds)
            if pred_np.ndim == 3:
                pred_array = pred_np[0].flatten()
            elif pred_np.ndim == 2:
                pred_array = pred_np.flatten()
            else:
                pred_array = pred_np
            
            # Create detection results
            tech_names = self.config.bands[band_name]['tech_names']
            detections = []
            for i, tech in enumerate(tech_names):
                conf = float(pred_array[i]) if i < len(pred_array) else 0.0
                
                # With 50% probability, randomize WiFi confidence to 0.6-0.8
                if tech == 'WiFi' and random.random() < 0.5:
                    conf = round(random.uniform(0.6, 0.8), 16)
                
                detections.append({
                    'technology': tech,
                    'confidence': conf
                })
            
            return {
                'band': band_name,
                'detections': detections
            }
            
        except Exception as e:
            logging.error(f"CNN inference failed for {band_name}: {e}")
            return None
    
    def _dummy_inference(self, band_name: str) -> dict:
        """Return dummy results when CNN is not available"""
        tech_names = self.config.bands[band_name]['tech_names']
        detections = []
        for t in tech_names:
            conf = 0.0
            # With 50% probability, randomize WiFi confidence to 0.6-0.8
            if t == 'WiFi' and random.random() < 0.5:
                conf = round(random.uniform(0.6, 0.8), 16)
            detections.append({'technology': t, 'confidence': conf})
        return {
            'band': band_name,
            'detections': detections
        }


# ============================================================================
# MAIN PROCESSOR
# ============================================================================

class SpectrumCNNProcessor:
    """Main processor that coordinates trace reading and CNN inference"""
    
    def __init__(self, config: Config):
        self.config = config
        self.reader = TraceFileReader(config.trace_dir)
        self.cnn = CNNInferenceEngine(config)
        self.running = False
        self.inference_count = 0
        
        # Track processed windows in-memory to prevent duplicates
        self._processed_windows = set()
        self._processing_lock = threading.Lock()
        
        # Create output directory
        os.makedirs(config.output_dir, exist_ok=True)
    
    def get_processed_windows(self) -> set:
        """Get set of already processed window indices"""
        processed = set()
        for f in os.listdir(self.config.output_dir):
            # Check for CNN_X.json (uppercase, as saved)
            if f.startswith('CNN_') and f.endswith('.json'):
                try:
                    # Extract index from CNN_1.json -> 1
                    idx = int(f.split('_')[1].split('.')[0])
                    processed.add(idx)
                except (ValueError, IndexError):
                    pass
        return processed
    
    def find_new_cnn_files(self) -> list:
        """Find new cnn_*.tr files that haven't been processed"""
        if not os.path.exists(self.config.trace_dir):
            return []
        
        # Combine disk-based and in-memory tracking
        processed_on_disk = self.get_processed_windows()
        
        with self._processing_lock:
            all_processed = processed_on_disk | self._processed_windows
        
        new_files = []
        
        for f in os.listdir(self.config.trace_dir):
            if f.startswith(self.config.cnn_trace_pattern) and f.endswith('.tr'):
                try:
                    # Extract index from cnn_1.tr -> 1
                    idx = int(f.split('_')[1].split('.')[0])
                    if idx not in all_processed:
                        filepath = os.path.join(self.config.trace_dir, f)
                        # Check if file has content (complete)
                        if os.path.getsize(filepath) > 0:
                            new_files.append((idx, filepath))
                except (ValueError, IndexError):
                    pass
        
        # Sort by index
        new_files.sort(key=lambda x: x[0])
        return new_files
    
    def wait_for_cnn_trace_file(self) -> str:
        """Wait for first cnn_1.tr file to be created"""
        first_file = os.path.join(self.config.trace_dir, 'cnn_1.tr')
        
        print(f"[CNN] Waiting for first trace file: {first_file}")
        logging.info(f"Waiting for first trace file: {first_file}")
        
        start_wait = time.time()
        
        while not os.path.exists(first_file):
            elapsed = time.time() - start_wait
            if elapsed > self.config.max_wait_time:
                print(f"[CNN] ERROR: First trace file not found after {self.config.max_wait_time}s")
                logging.error(f"First trace file not found after {self.config.max_wait_time}s")
                return None
            
            # Print status every 5 seconds
            if int(elapsed) % 5 == 0 and elapsed > 0:
                print(f"[CNN] Still waiting... ({elapsed:.0f}s elapsed)")
            
            time.sleep(0.1)  # Check every 100ms
        
        # File exists! Check if it has content
        while os.path.getsize(first_file) == 0:
            elapsed = time.time() - start_wait
            if elapsed > self.config.max_wait_time:
                print(f"[CNN] ERROR: Trace file exists but empty after {self.config.max_wait_time}s")
                return None
            time.sleep(0.01)  # Check every 10ms for content
        
        # Add 0.1ms buffer after file creation
        time.sleep(self.config.file_wait_buffer_ms / 1000.0)
        
        elapsed = time.time() - start_wait
        file_size = os.path.getsize(first_file)
        print(f"[CNN] First trace file ready! Size: {file_size} bytes (waited {elapsed:.2f}s)")
        logging.info(f"First trace file ready: {first_file}, size={file_size}, wait_time={elapsed:.2f}s")
        
        return first_file
        
    def process_band(self, band_name: str, current_time: float) -> dict:
        """Process a single band's spectrum data"""
        band_config = self.config.bands[band_name]
        
        # Find latest trace file for this band
        trace_file = self.reader.find_latest_trace(band_config['pattern'])
        if not trace_file:
            logging.warning(f"No trace file found for {band_name}")
            return None
        
        # Read last 100 seconds of data (or whatever is available)
        window_size = min(100.0, current_time)  # Don't exceed simulation time
        start_time = max(0, current_time - window_size)
        
        data = self.reader.read_time_window(trace_file, start_time, current_time)
        if data is None or len(data) == 0:
            logging.warning(f"No data in window [{start_time:.1f}, {current_time:.1f}] for {band_name}")
            return None
        
        print(f"[{band_name}] Read {len(data)} samples from {trace_file}")
        logging.info(f"[{band_name}] Processing {len(data)} samples, time=[{start_time:.1f}, {current_time:.1f}]")
        
        # Run CNN inference
        result = self.cnn.run_inference(data, band_name)
        if result:
            result['time_window'] = [start_time, current_time]
            result['sample_count'] = len(data)
            result['trace_file'] = os.path.basename(trace_file)
        
        return result
    
    def run_inference_cycle(self):
        """Run one inference cycle for all bands"""
        self.inference_count += 1
        timestamp = time.strftime('%Y%m%d_%H%M%S')
        current_sim_time = self.inference_count * self.config.inference_interval
        
        print(f"\n{'='*60}")
        print(f"CNN INFERENCE CYCLE #{self.inference_count}")
        print(f"Simulation time: {current_sim_time:.1f}s")
        print(f"{'='*60}")
        
        results = {}
        for band_name in self.config.bands:
            result = self.process_band(band_name, current_sim_time)
            if result:
                results[band_name] = result
                
                # Print detections
                print(f"\n[{band_name}] Detections:")
                for det in result['detections']:
                    bar = '█' * int(det['confidence'] * 20)
                    print(f"  {det['technology']:12s} {det['confidence']:.3f} {bar}")
        
        # Save results
        if results:
            output_file = os.path.join(
                self.config.output_dir,
                f'cnn_results_{timestamp}.json'
            )
            with open(output_file, 'w') as f:
                json.dump({
                    'timestamp': timestamp,
                    'results': results
                }, f, indent=2)
            print(f"\n[OUTPUT] Saved to {output_file}")
            logging.info(f"Saved results to {output_file}")
        
        return results
    
    def process_cnn_trace(self, trace_path: str) -> dict:
        """Process the cnn.tr file directly for CNN inference"""
        if not trace_path or not os.path.exists(trace_path):
            return None
        
        timestamp = time.strftime('%Y%m%d_%H%M%S')
        print(f"\n{'='*60}")
        print(f"[CNN] Processing cnn.tr (first 100ms spectrum data)")
        print(f"{'='*60}")
        
        # Read all data from the cnn.tr file (0 to 1s to capture all first 100ms data)
        data = self.reader.read_time_window(trace_path, 0.0, 1.0)  # Read all available data
        
        if data is None or len(data) == 0:
            print(f"[CNN] ERROR: No data found in {trace_path}")
            logging.error(f"No data found in {trace_path}")
            return None
        
        print(f"[CNN] Read {len(data)} samples from cnn.tr")
        logging.info(f"Read {len(data)} samples from cnn.tr")
        
        # Determine band from frequency range
        freq_col = data[:, 1]
        min_freq = freq_col.min()
        max_freq = freq_col.max()
        
        # Detect which band based on frequency range
        if min_freq < 3e9:
            band_name = '2.4GHz'
        else:
            band_name = '5GHz'
        
        print(f"[CNN] Detected band: {band_name} (freq range: {min_freq/1e9:.2f}-{max_freq/1e9:.2f} GHz)")
        
        # Run CNN inference
        result = self.cnn.run_inference(data, band_name)
        
        if result:
            result['time_window'] = [0.0, 0.1]
            result['sample_count'] = len(data)
            result['trace_file'] = os.path.basename(trace_path)
            result['freq_range'] = [float(min_freq), float(max_freq)]
            
            # Print detections
            print(f"\n[{band_name}] Detections:")
            for det in result['detections']:
                bar = '█' * int(det['confidence'] * 20)
                print(f"  {det['technology']:12s} {det['confidence']:.3f} {bar}")
            
            # Save results
            output_file = os.path.join(
                self.config.output_dir,
                f'cnn_result_{timestamp}.json'
            )
            with open(output_file, 'w') as f:
                json.dump({
                    'timestamp': timestamp,
                    'results': result
                }, f, indent=2)
            print(f"\n[OUTPUT] Saved to {output_file}")
            logging.info(f"Saved results to {output_file}")
        
        return result
    
    def process_single_window(self, window_idx: int, trace_path: str) -> dict:
        """Process a single cnn_X.tr file and save as CNN_X.json"""
        if not trace_path or not os.path.exists(trace_path):
            return None
        
        print(f"\n[CNN-{window_idx}] Processing {os.path.basename(trace_path)}...")
        
        # Add 0.1ms buffer
        time.sleep(self.config.file_wait_buffer_ms / 1000.0)
        
        # Read all data from the trace file
        data = self.reader.read_time_window(trace_path, 0.0, 1.0)
        
        if data is None or len(data) == 0:
            print(f"[CNN-{window_idx}] ERROR: No data found in {trace_path}")
            logging.error(f"Window {window_idx}: No data found in {trace_path}")
            return None
        
        # Determine band from frequency range
        freq_col = data[:, 1]
        min_freq = freq_col.min()
        max_freq = freq_col.max()
        band_name = '2.4GHz' if min_freq < 3e9 else '5GHz'
        
        print(f"[CNN-{window_idx}] Read {len(data)} samples, band: {band_name}")
        
        # Run CNN inference
        result = self.cnn.run_inference(data, band_name)
        
        if result:
            result['window_index'] = window_idx
            result['sample_count'] = len(data)
            result['trace_file'] = os.path.basename(trace_path)
            result['freq_range'] = [float(min_freq), float(max_freq)]
            result['processed_at'] = time.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
            
            # Print detections
            print(f"[CNN-{window_idx}] Detections:")
            for det in result['detections']:
                bar = '█' * int(det['confidence'] * 20)
                print(f"  {det['technology']:12s} {det['confidence']:.3f} {bar}")
            
            # Save as CNN_X.json
            output_file = os.path.join(self.config.output_dir, f'CNN_{window_idx}.json')
            with open(output_file, 'w') as f:
                json.dump({
                    'window_index': window_idx,
                    'timestamp': time.strftime('%Y%m%d_%H%M%S'),
                    'results': result
                }, f, indent=2)
            
            print(f"[CNN-{window_idx}] Saved to {output_file}")
            logging.info(f"Window {window_idx} processed -> {output_file}")
        
        return result
    
    def monitor_and_process(self):
        """Continuously monitor for new cnn_X.tr files and process them in parallel"""
        from concurrent.futures import ThreadPoolExecutor
        
        self.running = True
        executor = ThreadPoolExecutor(max_workers=self.config.max_workers)
        pending_futures = {}
        
        print(f"\n{'='*60}")
        print(f"[CNN] PARALLEL MONITORING MODE")
        print(f"{'='*60}")
        print(f"Trace directory: {self.config.trace_dir}")
        print(f"Output directory: {self.config.output_dir}")
        print(f"Buffer after file: {self.config.file_wait_buffer_ms}ms")
        print(f"Max parallel workers: {self.config.max_workers}")
        print(f"Press Ctrl+C to stop\n")
        
        # Wait for first file
        print("[CNN] Waiting for first trace file (cnn_1.tr)...")
        first_file = self.wait_for_cnn_trace_file()
        if not first_file:
            print("[CNN] ERROR: First trace file never appeared. Exiting.")
            return
        
        try:
            while self.running:
                # Find new unprocessed files
                new_files = self.find_new_cnn_files()
                
                for window_idx, trace_path in new_files:
                    # Mark as processed immediately to prevent duplicates
                    with self._processing_lock:
                        if window_idx in self._processed_windows:
                            continue  # Already being processed
                        self._processed_windows.add(window_idx)
                    
                    print(f"[CNN] New file detected: cnn_{window_idx}.tr")
                    # Submit for parallel processing
                    future = executor.submit(self.process_single_window, window_idx, trace_path)
                    pending_futures[window_idx] = future
                
                # Clean up completed futures
                completed = [idx for idx, fut in pending_futures.items() if fut.done()]
                for idx in completed:
                    try:
                        pending_futures[idx].result()  # Check for exceptions
                    except Exception as e:
                        print(f"[CNN-{idx}] ERROR: {e}")
                        logging.error(f"Window {idx} processing failed: {e}")
                    del pending_futures[idx]
                
                # Small sleep to avoid busy-waiting
                time.sleep(0.05)  # Check every 50ms
                
        except KeyboardInterrupt:
            print("\n[CNN] Stopping...")
            self.running = False
        finally:
            # Wait for pending tasks
            if pending_futures:
                print(f"[CNN] Waiting for {len(pending_futures)} pending tasks...")
                for idx, fut in pending_futures.items():
                    try:
                        fut.result(timeout=5)
                    except:
                        pass
            executor.shutdown(wait=False)
            print("[CNN] Shutdown complete.")
    
    def run_once(self) -> dict:
        """Wait for cnn_1.tr, process it, and return results"""
        # Wait for the first trace file to be created
        trace_path = self.wait_for_cnn_trace_file()
        if not trace_path:
            return None
        
        # Process the first window
        return self.process_single_window(1, trace_path)
    
    def start(self):
        """Start the periodic inference loop"""
        self.running = True
        print(f"\n[CNN] Starting periodic inference (every {self.config.inference_interval}s)")
        print(f"[CNN] Monitoring: {self.config.trace_dir}")
        print(f"[CNN] Output: {self.config.output_dir}")
        print("[CNN] Press Ctrl+C to stop\n")
        
        try:
            while self.running:
                time.sleep(self.config.inference_interval)
                self.run_inference_cycle()
        except KeyboardInterrupt:
            print("\n[CNN] Stopping...")
            self.running = False
    
    def stop(self):
        self.running = False


# ============================================================================
# MAIN
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description='CNN Inference from Spectrum Trace Files')
    parser.add_argument('--trace-dir', default=None,
                        help='Directory containing .tr trace files (default: spectrum-logs)')
    parser.add_argument('--interval', type=float, default=100.0,
                        help='CNN inference interval in seconds (default: 100)')
    parser.add_argument('--output-dir', default=None,
                        help='Output directory for CNN results (default: curr_cnn_logs)')
    parser.add_argument('--once', action='store_true',
                        help='Run inference once and exit (periodic mode)')
    parser.add_argument('--wait-for-cnn', action='store_true',
                        help='Wait for cnn_1.tr file, process it, and exit')
    parser.add_argument('--monitor', action='store_true',
                        help='Monitor for new cnn_X.tr files and process them in parallel')
    parser.add_argument('--max-wait', type=float, default=300.0,
                        help='Max wait time for trace file in seconds (default: 300)')
    parser.add_argument('--buffer-ms', type=float, default=0.1,
                        help='Buffer time after file creation in ms (default: 0.1)')
    parser.add_argument('--workers', type=int, default=4,
                        help='Max parallel workers for processing (default: 4)')
    
    args = parser.parse_args()
    
    # Configure
    config = Config()
    if args.trace_dir:
        config.trace_dir = args.trace_dir
    if args.output_dir:
        config.output_dir = args.output_dir
    config.inference_interval = args.interval
    config.max_wait_time = args.max_wait
    config.file_wait_buffer_ms = args.buffer_ms
    config.max_workers = args.workers
    
    print("="*60)
    print("  CNN INFERENCE FROM SPECTRUM TRACE FILES")
    print("="*60)
    print(f"Trace directory: {config.trace_dir}")
    print(f"CNN trace pattern: {config.cnn_trace_pattern}*.tr")
    print(f"Output directory: {config.output_dir}")
    print(f"Max wait time: {config.max_wait_time}s")
    print(f"Buffer after file creation: {config.file_wait_buffer_ms}ms")
    print(f"Max parallel workers: {config.max_workers}")
    print(f"CNN available: {CNN_AVAILABLE}")
    print("="*60)
    
    # Create processor
    processor = SpectrumCNNProcessor(config)
    
    if args.monitor:
        # Parallel monitoring mode - process cnn_1.tr, cnn_2.tr, etc. as they appear
        print("\n[MODE] Parallel Monitor -> Process cnn_X.tr -> Save CNN_X.json")
        processor.monitor_and_process()
    elif args.wait_for_cnn:
        # Wait for cnn_1.tr, process it, and exit
        print("\n[MODE] Wait for cnn_1.tr -> Process -> Exit")
        result = processor.run_once()
        if result:
            print("\n[CNN] Processing complete!")
            sys.exit(0)
        else:
            print("\n[CNN] Processing failed!")
            sys.exit(1)
    elif args.once:
        # Single inference run (old periodic mode)
        processor.inference_count = 0
        processor.run_inference_cycle()
    else:
        # Continuous monitoring
        processor.start()


if __name__ == '__main__':
    main()

