/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
/*
 * Copyright (c) 2025
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include "spectrum-analyser-logger.h"
#include "ns3/log.h"
#include "ns3/simulator.h"
#include <iostream>
#include <sstream>
#include <fstream>
#include <iomanip>
#include <unistd.h>

namespace ns3 {

NS_LOG_COMPONENT_DEFINE ("SpectrumAnalyserLogger");

NS_OBJECT_ENSURE_REGISTERED (SpectrumAnalyserLogger);

// Initialize static members (multi-band shared files)
std::map<std::string, SpectrumAnalyserLogger::SharedFileInfo> SpectrumAnalyserLogger::s_sharedFiles;

void
SpectrumAnalyserLogger::EnableSharedFile(const std::string& bandId, const std::string& filePath)
{
  NS_LOG_FUNCTION(bandId << filePath);

  // Close existing file for this band if open
  if (s_sharedFiles.find(bandId) != s_sharedFiles.end())
    {
      if (s_sharedFiles[bandId].file && s_sharedFiles[bandId].file->is_open())
        {
          s_sharedFiles[bandId].file->close();
          delete s_sharedFiles[bandId].file;
        }
    }

  // Create new shared file info
  SharedFileInfo info;
  info.filePath = filePath;
  info.file = new std::ofstream(filePath.c_str());
  info.initialized = false;

  if (info.file->is_open())
    {
      info.initialized = true;
      // Write header
      *info.file << "# Spectrum PSD Trace File (.tr format)\n";
      *info.file << "# Band: " << bandId << "\n";
      *info.file << "# Format: node_id time_sec freq_hz psd_w_hz\n";
      *info.file << "# Generated by ns-3 SpectrumAnalyserLogger\n";
      NS_LOG_INFO("Shared .tr file opened for band '" << bandId << "': " << filePath);
    }
  else
    {
      NS_LOG_ERROR("Failed to open shared .tr file for band '" << bandId << "': " << filePath);
      delete info.file;
      info.file = nullptr;
    }

  s_sharedFiles[bandId] = info;
}

void
SpectrumAnalyserLogger::EnableSharedFile(const std::string& filePath)
{
  // Legacy single-argument version uses "default" band
  EnableSharedFile("default", filePath);
}

void
SpectrumAnalyserLogger::DisableSharedFile(const std::string& bandId)
{
  NS_LOG_FUNCTION(bandId);
  CloseSharedFile(bandId);
  s_sharedFiles.erase(bandId);
}

void
SpectrumAnalyserLogger::DisableSharedFile()
{
  NS_LOG_FUNCTION_NOARGS();
  CloseSharedFile();
  s_sharedFiles.clear();
}

bool
SpectrumAnalyserLogger::IsSharedFileEnabled()
{
  return !s_sharedFiles.empty();
}

bool
SpectrumAnalyserLogger::IsSharedFileEnabled(const std::string& bandId)
{
  auto it = s_sharedFiles.find(bandId);
  return (it != s_sharedFiles.end() && it->second.initialized);
}

std::string
SpectrumAnalyserLogger::GetSharedFilePath(const std::string& bandId)
{
  auto it = s_sharedFiles.find(bandId);
  if (it != s_sharedFiles.end())
    {
      return it->second.filePath;
    }
  return "";
}

std::string
SpectrumAnalyserLogger::GetSharedFilePath()
{
  // Legacy: return default band path
  return GetSharedFilePath("default");
}

void
SpectrumAnalyserLogger::CloseSharedFile(const std::string& bandId)
{
  NS_LOG_FUNCTION(bandId);
  auto it = s_sharedFiles.find(bandId);
  if (it != s_sharedFiles.end() && it->second.file)
    {
      if (it->second.file->is_open())
        {
          it->second.file->flush();
          it->second.file->close();
        }
      delete it->second.file;
      it->second.file = nullptr;
      it->second.initialized = false;
      NS_LOG_INFO("Shared .tr file closed for band '" << bandId << "'");
    }
}

void
SpectrumAnalyserLogger::CloseSharedFile()
{
  NS_LOG_FUNCTION_NOARGS();
  for (auto& pair : s_sharedFiles)
    {
      if (pair.second.file)
        {
          if (pair.second.file->is_open())
            {
              pair.second.file->flush();
              pair.second.file->close();
            }
          delete pair.second.file;
          pair.second.file = nullptr;
          pair.second.initialized = false;
        }
    }
  NS_LOG_INFO("All shared .tr files closed");
}

void
SpectrumAnalyserLogger::WriteEndMarker(const std::string& bandId, double timestamp)
{
  NS_LOG_FUNCTION(bandId << timestamp);
  auto it = s_sharedFiles.find(bandId);
  if (it != s_sharedFiles.end() && it->second.file && it->second.file->is_open())
    {
      // Write END marker with exact stop timestamp
      // Format: "# END <timestamp>" - comment line that parsers can use to know exact stop time
      *it->second.file << "# END " << timestamp << "\n";
      it->second.file->flush();
      NS_LOG_INFO("Wrote END marker at t=" << timestamp << "s to band '" << bandId << "'");
    }
}

void
SpectrumAnalyserLogger::WriteEndMarker(double timestamp)
{
  NS_LOG_FUNCTION(timestamp);
  for (auto& pair : s_sharedFiles)
    {
      if (pair.second.file && pair.second.file->is_open())
        {
          *pair.second.file << "# END " << timestamp << "\n";
          pair.second.file->flush();
          NS_LOG_INFO("Wrote END marker at t=" << timestamp << "s to band '" << pair.first << "'");
        }
    }
}

void
SpectrumAnalyserLogger::CloseSharedFileWithTimestamp(const std::string& bandId, double finalTimestamp)
{
  NS_LOG_FUNCTION(bandId << finalTimestamp);
  WriteEndMarker(bandId, finalTimestamp);
  CloseSharedFile(bandId);
}

void
SpectrumAnalyserLogger::CloseAllSharedFilesWithTimestamp(double finalTimestamp)
{
  NS_LOG_FUNCTION(finalTimestamp);
  WriteEndMarker(finalTimestamp);
  CloseSharedFile();
}

void
SpectrumAnalyserLogger::SetBandId(const std::string& bandId)
{
  m_bandId = bandId;
}

TypeId
SpectrumAnalyserLogger::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::SpectrumAnalyserLogger")
    .SetParent<Object> ()
    .SetGroupName ("SpectrumAnalyserLogger")
    .AddConstructor<SpectrumAnalyserLogger> ()
  ;
  return tid;
}

SpectrumAnalyserLogger::SpectrumAnalyserLogger ()
  : m_loggingInterval (MilliSeconds (100)),  // Default: 100ms
    m_lastLogTime (Seconds (0.0)),
    m_outputFilename (""),
    m_nodeId (0),
    m_consoleOutput (false),
    m_fileOutputEnabled (false)
{
  NS_LOG_FUNCTION (this);
}

SpectrumAnalyserLogger::~SpectrumAnalyserLogger ()
{
  NS_LOG_FUNCTION (this);
  if (m_outputFile.is_open ())
    {
      m_outputFile.close ();
    }
}

void
SpectrumAnalyserLogger::SetLoggingInterval (Time interval)
{
  NS_LOG_FUNCTION (this << interval);
  m_loggingInterval = interval;
}

Time
SpectrumAnalyserLogger::GetLoggingInterval (void) const
{
  return m_loggingInterval;
}

void
SpectrumAnalyserLogger::SetOutputFile (const std::string& filename)
{
  NS_LOG_FUNCTION (this << filename);
  m_outputFilename = filename;

  // Close existing file if open
  if (m_outputFile.is_open ())
    {
      m_outputFile.close ();
    }

  // Open new file
  m_outputFile.open (filename.c_str ());
  if (m_outputFile.is_open ())
    {
      m_fileOutputEnabled = true;
      // Write header
      m_outputFile << "# Spectrum Analyzer Logger Data\n";
      m_outputFile << "# NodeId: " << m_nodeId << "\n";
      m_outputFile << "# Format: Timestamp(s) Frequency(Hz) PSD(W/Hz)\n";
      NS_LOG_INFO ("Opened output file: " << filename);
    }
  else
    {
      NS_LOG_ERROR ("Failed to open output file: " << filename);
      m_fileOutputEnabled = false;
    }
}

void
SpectrumAnalyserLogger::SetNodeId (uint32_t nodeId)
{
  NS_LOG_FUNCTION (this << nodeId);
  m_nodeId = nodeId;
}

void
SpectrumAnalyserLogger::SetConsoleOutput (bool enable)
{
  NS_LOG_FUNCTION (this << enable);
  m_consoleOutput = enable;
}

void
SpectrumAnalyserLogger::PsdCallback (Ptr<const SpectrumValue> psd)
{
  NS_LOG_FUNCTION (this << psd);

  double timestamp = Simulator::Now ().GetSeconds ();

  // Check if enough time has passed since last log
  if ((timestamp - m_lastLogTime.GetSeconds ()) < m_loggingInterval.GetSeconds ())
    {
      return;
    }

  m_lastLogTime = Seconds (timestamp);

  // Write PSD data
  WritePsdData (timestamp, psd);
}

void
SpectrumAnalyserLogger::WritePsdData (double timestamp, Ptr<const SpectrumValue> psd)
{
  NS_LOG_FUNCTION (this << timestamp << psd);

  // Wait for basic-simulation to reach this timestamp (sync barrier)
  const double tolerance = 0.05;  // 50ms tolerance
  int maxWait = 1000;  // Max 10s wait (1000 * 10ms)
  for (int i = 0; i < maxWait; i++)
    {
      std::ifstream syncFile("/tmp/ns3-sync-timestamp.txt");
      double leaderTime = 0.0;
      if (syncFile >> leaderTime && leaderTime >= timestamp - tolerance)
        {
          break;  // Leader caught up, proceed with write
        }
      syncFile.close();
      usleep(10000);  // Wait 10ms and check again
    }

  if (!psd)
    {
      NS_LOG_WARN ("Received null PSD pointer");
      return;
    }

  Values::const_iterator it = psd->ConstValuesBegin ();
  Bands::const_iterator bit = psd->ConstBandsBegin ();

  while (it != psd->ConstValuesEnd ())
    {
      double frequency = bit->fc;  // Center frequency
      double psdValue = (*it);      // PSD value in W/Hz

      // Write to shared .tr file if enabled (format: node_id time freq psd)
      auto sharedIt = s_sharedFiles.find(m_bandId.empty() ? "default" : m_bandId);
      if (sharedIt != s_sharedFiles.end() && sharedIt->second.initialized && sharedIt->second.file && sharedIt->second.file->is_open())
        {
          *sharedIt->second.file << m_nodeId << " "
                                 << timestamp << " "
                                 << frequency << " "
                                 << psdValue << "\n";
        }

      // Write to per-node file if enabled (original behavior)
      if (m_fileOutputEnabled && m_outputFile.is_open ())
        {
          m_outputFile << timestamp << " "
                      << frequency << " "
                      << psdValue << std::endl;
        }

      // Write to console if enabled
      if (m_consoleOutput)
        {
          std::cout << "Node" << m_nodeId << " "
                    << timestamp << " "
                    << frequency << " "
                    << psdValue << std::endl;
        }

      ++it;
      ++bit;
    }

  // Flush shared file periodically
  auto flushIt = s_sharedFiles.find(m_bandId.empty() ? "default" : m_bandId);
  if (flushIt != s_sharedFiles.end() && flushIt->second.initialized && flushIt->second.file && flushIt->second.file->is_open())
    {
      flushIt->second.file->flush();
    }

  // Flush per-node file buffer periodically for real-time monitoring
  if (m_fileOutputEnabled && m_outputFile.is_open ())
    {
      m_outputFile.flush ();
    }

  // Write spectrum-shadow sync timestamp for bidirectional synchronization
  // This allows basic-simulation to wait for spectrum-shadow to catch up
  {
    std::ofstream spectrumSyncFile("/tmp/ns3-spectrum-sync-timestamp.txt", std::ios::trunc);
    if (spectrumSyncFile.is_open())
      {
        spectrumSyncFile << std::fixed << std::setprecision(6) << timestamp;
        spectrumSyncFile.close();
      }
  }
}

} // namespace ns3
